modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="rather_more_potions"
version="1.0.0"
displayName="Rather More Potions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://donmor.top/"
authors="donmor3000"

[[dependencies.rather_more_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




